# frozen_string_literal: true

#/ -----------------------------------------------------------------------------
#/ settings

cask_args appdir: "/Applications", require_sha: true

#/ -----------------------------------------------------------------------------
#/ brew taps - none

#/ -----------------------------------------------------------------------------
#/ brew install

brew "bash"

brew "sevenzip"
brew "gnu-tar"
brew "gzip"
brew "pigz"
brew "uv"

brew "container"
brew "coreutils"
brew "duti"
brew "jq"
brew "pv"
brew "tree"
brew "yq"

brew "exiftool"
brew "ffmpeg"
brew "ghostscript"
brew "imagemagick"
brew "pandoc"
brew "weasyprint"

brew "gh"
brew "git"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
brew "git-sizer"
brew "gitmoji"

brew "gnupg"
brew "openssh"
brew "openssl@3"
brew "pinentry-mac"
brew "ykman"
brew "yubikey-agent"

brew "go"
brew "golangci-lint"
brew "goreleaser"

brew "node"
brew "nvm"

brew "rbenv"

brew "pyenv"
brew "pipenv"
# brew "virtualenv"

brew "readline"
brew "rg"
brew "xz"
brew "tcl-tk"
brew "libb2"
brew "zstd"
brew "zlib"

#/ -----------------------------------------------------------------------------
#/ brew install --cask

cask "1password"
cask "1password-cli"
cask "alfred"
cask "apparency"
cask "cleanmymac"
cask "cleanshot"
cask "copilot-cli@prerelease"
cask "cyberduck"
cask "docker-desktop"
cask "elgato-camera-hub"
cask "elgato-stream-deck"
cask "insomnia"
cask "istat-menus"
cask "kaleidoscope"
cask "kap"
cask "little-snitch"
cask "micro-snitch"
cask "microsoft-auto-update"
cask "mosaic"
cask "muzzle"
cask "rectangle-pro"
cask "rocket"
cask "spotify", args: { require_sha: false }
cask "suspicious-package"
cask "the-unarchiver"
cask "tower"
cask "ubersicht"
cask "visual-studio-code"
cask "visual-studio-code@insiders"

#/ -----------------------------------------------------------------------------
#/ fonts

cask "font-fira-code-nerd-font"
cask "font-fira-code"
cask "font-hubot-sans"
cask "font-mona-sans"
cask "font-monaspace"

#/ -----------------------------------------------------------------------------
#/ mas install

brew "mas"

mas "1Password for Safari", id: 1569813296
# mas "Bear", id: 1091189122
mas "Dato", id: 1470584107
mas "Denied", id: 909257784
# mas "Gifski", id: 1351639930
mas "Speediness", id: 1596706466
# mas "Xcode", id: 497799835
