inherit_from: []

inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  CacheRootDirectory: ./tmp
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - '.bundle/**/*'
  ExtraDetails: true
  NewCops: disable
  RubyInterpreters:
    - ruby
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Naming/FileName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
