inherit_from: []

AllCops:
  RubyInterpreters:
    - ruby

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
