#!/bin/zsh

set -eo pipefail

source "${DFH}/inc/helpers.zsh"

if ! which duti &> /dev/null; then
  print -P "✘ %178Faborting%f Please \`brew install duti\` first"
  return 1
fi

print -P "ℹ %178FSetting default file associations for VSCode%f"

formatexec "duti -s com.microsoft.VSCode public.json all"
formatexec "duti -s com.microsoft.VSCode public.plain-text all"
formatexec "duti -s com.microsoft.VSCode public.python-script all"
formatexec "duti -s com.microsoft.VSCode public.shell-script all"
formatexec "duti -s com.microsoft.VSCode public.source-code all"
formatexec "duti -s com.microsoft.VSCode public.text all"
formatexec "duti -s com.microsoft.VSCode public.unix-executable all"
formatexec "duti -s com.microsoft.VSCode public.data all"

formatexec "duti -s com.microsoft.VSCode .c all"
formatexec "duti -s com.microsoft.VSCode .cfg all"
formatexec "duti -s com.microsoft.VSCode .conf all"
formatexec "duti -s com.microsoft.VSCode .cpp all"
formatexec "duti -s com.microsoft.VSCode .cs all"
formatexec "duti -s com.microsoft.VSCode .css all"
formatexec "duti -s com.microsoft.VSCode .go all"
formatexec "duti -s com.microsoft.VSCode .java all"
formatexec "duti -s com.microsoft.VSCode .js all"
formatexec "duti -s com.microsoft.VSCode .json all"
formatexec "duti -s com.microsoft.VSCode .jsx all"
formatexec "duti -s com.microsoft.VSCode .less all"
formatexec "duti -s com.microsoft.VSCode .log all"
formatexec "duti -s com.microsoft.VSCode .lua all"
formatexec "duti -s com.microsoft.VSCode .md all"
formatexec "duti -s com.microsoft.VSCode .php all"
formatexec "duti -s com.microsoft.VSCode .pl all"
formatexec "duti -s com.microsoft.VSCode .py all"
formatexec "duti -s com.microsoft.VSCode .rb all"
formatexec "duti -s com.microsoft.VSCode .sass all"
formatexec "duti -s com.microsoft.VSCode .scss all"
formatexec "duti -s com.microsoft.VSCode .sh all"
formatexec "duti -s com.microsoft.VSCode .toml all"
formatexec "duti -s com.microsoft.VSCode .ts all"
formatexec "duti -s com.microsoft.VSCode .tsx all"
formatexec "duti -s com.microsoft.VSCode .txt all"
formatexec "duti -s com.microsoft.VSCode .vue all"
formatexec "duti -s com.microsoft.VSCode .xml all"
formatexec "duti -s com.microsoft.VSCode .yaml all"
formatexec "duti -s com.microsoft.VSCode .yml all"
formatexec "duti -s com.microsoft.VSCode .zsh all"
