#!/usr/bin/env zsh

# get default version
FILE="${HOME}/.nvm/alias/default"
VERSION=v$(cat "${FILE}")

# define SOURCE and TARGET
src="${HOME}/.nvm/${VERSION}/bin/node"
dest="${HOME}/bin/node"

# cleanup old symlink
rm "${dest}" > /dev/null 2>&1

# link it
print -P "linking %F{yellow}${src}%f to %F{green}${dest}%f"
ln -s "${src}" "${dest}"
