#!/bin/zsh

clear

# disabled
print -P "\n    %F{1}disabled%f."
exit 0

print -P "uninstalling %F{11}~/%f"

function section () {
    print -P "\n[ %F{4}$1%f ] $2"
}

function ok() {
    print -P "[ %F{2}%f ]\n"
}

function abort {
  print -P "\n%F{1}> $1%f first!"
  exit 1
}

# brew -------------------------------------------------------------------------
section "brew"

# casks
for CASK in $(brew cask list); do
    brew cask zap "$CASK" > /dev/null 2>&1
    print -P "    %F{1}✗%f cask %F{4}$CASK%f removed"
done

# brews
for BREW in $(brew list); do
    brew uninstall "$BREW" > /dev/null 2>&1
    print -P "    %F{1}✗%f %F{4}$BREW%f removed"
done

brew prune
brew cleanup

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

sudo chmod 0755 /usr/local
sudo chgrp wheel /usr/local

ok

# antigen ----------------------------------------------------------------------
section "antigen"

[ -d "~/.antigen" ] && rm -rf "~/.antigen"

ok

# done & reload ----------------------------------------------------------------
print -P "\n\nDONE."
print -P "\n%F{8}  with %F{1}%F{8} by %F{12}stoe%F{8} (https://github.com/stoe/.dotfiles)%f"
exec $SHELL -l
