# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: code --wait
# Aliases allow you to create nicknames for gh commands
aliases:
    browse: repo view --web
    clone: repo clone
    co: pr checkout
    comment: issue comment -e
    notes: issue list -l "meeting-notes ☑"
    pr: pull request
    repo-list: |-
        api graphql -F owner="$1" -f query="
            query ($owner: String!, $endCursor: String = null) {
              organization(login: $owner) {
                repositories(first: 10, orderBy: { field: NAME, direction: ASC }, after: $endCursor) {
                  nodes {
                    name
                    url
                  }
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                }
              }
            }
          " --jq ".data.organization.repositories.nodes[] | select(.object == null) | {\"name\": .name, \"url\": .url}"
