#!/bin/zsh

export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/lib:$PATH"
export PATH="/usr/local/sbin:$PATH"

export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

export PATH="$HOME/bin:$PATH"
