#!/bin/zsh

source $HOME/.antigen/antigen.zsh

# oh-my-zsh LIBRARY ------------------------------------------------------------
antigen use oh-my-zsh

# BUNDLES ----------------------------------------------------------------------
antigen bundle atom
antigen bundle brew
antigen bundle common-aliases
antigen bundle git
antigen bundle git-extras
antigen bundle git-flow
antigen bundle node
antigen bundle npm
antigen bundle osx

antigen bundle zsh-users/zsh-syntax-highlighting

[ -f "$HOME/.zshrc_local" ] && source "$HOME/.zshrc_local"

# THEME ------------------------------------------------------------------------
THEMES_HOME="$HOME/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/themes"
[ ! -f "$THEMES_HOME/stoe.zsh-theme" ] && ln -sf "$HOME/.dotfiles/zsh/stoe.zsh-theme" "$THEMES_HOME/stoe.zsh-theme"

for font in $HOME/.fonts/*.zsh; do
    source "$font"
done

antigen theme stoe

# NODE -------------------------------------------------------------------------
nvm="$HOME/.nvm"

[ ! -d "${nvm}" ] && mkdir "${nvm}"
[ ! -f "$HOME/.npmrc" ] && touch $HOME/.npmrc     # npm config file
export NVM_DIR="${nvm}"
source "$(brew --prefix nvm)/nvm.sh"

# RBENV ------------------------------------------------------------------------
export PATH="$HOME/.rbenv/bin:$PATH"
if type "rbenv" > /dev/null; then
  eval "$(rbenv init -)"
fi

# SOURCES ----------------------------------------------------------------------
for config in $(find $HOME/.dotfiles/etc -type f -name "*.zsh" -print | sed "s/^\.\///"); do
    # print -P "%F{8}$config%f"
    source $config
done
unset config

# STUFF ------------------------------------------------------------------------
zstyle ":completion:*" special-dirs true

# Make Atom.io the default editor
export EDITOR="atom -w"

# Larger bash history (allow 32³ entries; default is 500)
HISTFILE=$HOME/.zsh_history     # where to store zsh config
HISTSIZE=1024                   # big history
SAVEHIST=1024                   # big history
setopt append_history           # append
setopt hist_ignore_all_dups     # no duplicate
unsetopt hist_ignore_space      # ignore space prefixed commands
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, don't wait until shell exit
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword
# export HISTSIZE=32768
# export HISTFILESIZE=$HISTSIZE
# export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_AU.UTF-8"
export LC_ALL="en_AU.UTF-8"

# DONE -------------------------------------------------------------------------
antigen apply

# always dark mode
dark-mode --mode Dark
