#!/bin/zsh

source $HOME/.antigen/antigen.zsh

# oh-my-zsh LIBRARY ------------------------------------------------------------
antigen use oh-my-zsh

# BUNDLES ----------------------------------------------------------------------
antigen bundle atom
antigen bundle brew
antigen bundle common-aliases
antigen bundle git
antigen bundle git-extras
antigen bundle git-flow
antigen bundle node
antigen bundle npm
antigen bundle osx

antigen bundle zsh-users/zsh-syntax-highlighting

# THEME ------------------------------------------------------------------------
THEMES_HOME="$HOME/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/themes"
[ ! -f "$THEMES_HOME/stoe.zsh-theme" ] && ln -sf ~/.dotfiles/zsh/stoe.zsh-theme "$THEMES_HOME/stoe.zsh-theme"
antigen theme stoe

# NODE -------------------------------------------------------------------------
nvm="${HOME}/.nvm"

[ ! -d "${nvm}" ] && mkdir "${nvm}"
[ ! -f ~/.npmrc ] && touch ~/.npmrc     # npm config file
export NVM_DIR="${nvm}"
source "$(brew --prefix nvm)/nvm.sh"

# SOURCES ----------------------------------------------------------------------
for config in $(find ~/.dotfiles/etc -type f -name "*.zsh" -print | sed "s/^\.\///"); do
    #echo $config
    source $config
done
unset config

# STUFF ------------------------------------------------------------------------
zstyle ":completion:*" special-dirs true

# Make Atom.io the default editor
export EDITOR="atom -w"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# DONE -------------------------------------------------------------------------
antigen apply
