---
name: '🚨 Lint'

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    concurrency:
      group: super-linter-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - name: Lint It
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
